# Generated by Django 4.2.4 on 2024-05-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_remove_blogs_blog_tags_remove_blogs_canonical_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cate_slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
