# Generated by Django 4.2.4 on 2024-05-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_category_cate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_category',
            name='main_slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
