# Generated by Django 4.2.4 on 2024-06-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_main_category_main_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='works',
            options={'ordering': ['order'], 'verbose_name_plural': 'Our Work'},
        ),
        migrations.AddField(
            model_name='works',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='works',
            name='category_title',
            field=models.CharField(default='Wallpapers', max_length=100),
        ),
    ]
