# Generated by Django 4.2.4 on 2024-06-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_alter_works_options_works_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='caution',
            field=models.CharField(default='Mobile & Laptop', max_length=500),
        ),
    ]
