# Generated by Django 4.2.4 on 2024-06-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_product_caution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='caution',
            field=models.CharField(default='Advance 1000...', max_length=500),
        ),
    ]
