# Generated by Django 4.2.4 on 2024-06-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_alter_product_caution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='caution',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
