# Generated by Django 4.2.4 on 2024-06-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_rename_caution_product_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deposit',
            field=models.CharField(blank=True, default='On Demand Deposit', max_length=500),
        ),
    ]
