# Generated by Django 4.2.4 on 2024-06-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_alter_product_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='deposit',
        ),
        migrations.AddField(
            model_name='product',
            name='deposit_desc',
            field=models.TextField(blank=True, default='On Demand Deposit', max_length=500, null=True),
        ),
    ]
