# Generated by Django 4.2.4 on 2024-06-20 13:02

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0109_remove_product_deposit_product_deposit_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=22, max_length=30, prefix='build', unique=True)),
                ('name', models.CharField(default='CJS BHATIA...', max_length=100)),
                ('contact', models.CharField(default='+91-', max_length=100)),
                ('email', models.CharField(default='@gmail.com', max_length=100)),
                ('address', models.CharField(default='South Delhi...', max_length=100)),
                ('description', models.TextField(blank=True, default='about yourself...', null=True)),
                ('instagram', models.CharField(default='@instagram.com', max_length=100)),
                ('facebook', models.CharField(default='@facebook.com', max_length=100)),
                ('linkedin', models.CharField(default='@linkedin.com', max_length=100)),
                ('twitter', models.CharField(default='@twitter.com', max_length=100)),
                ('meta_description', models.CharField(max_length=100)),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_tag', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='12345678900', length=22, max_length=50, prefix='sku', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(null=True)),
                ('image', models.ImageField(default='builder.jpg', upload_to=core.models.user_directory_path)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Builder',
            },
        ),
        migrations.CreateModel(
            name='BuilderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='south ex..', max_length=100)),
                ('images', models.ImageField(default='architecture.jpg', upload_to='architecture-images')),
                ('date', models.DateField(auto_now_add=True)),
                ('builder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.builder')),
            ],
            options={
                'verbose_name_plural': 'Builder Project Images',
            },
        ),
    ]
