# Generated by Django 4.2.4 on 2024-07-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0110_builder_builderimages"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_name",
            name="ecommerce",
            field=models.BooleanField(default=False),
        ),
    ]
