# Generated by Django 4.2.4 on 2024-07-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_alter_cartorder_price_alter_cartorder_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gst_rate",
            field=models.CharField(default="18%", max_length=100),
        ),
    ]
