# Generated by Django 4.2.4 on 2024-07-31 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0113_product_gst_rate"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="gst_rate",),
    ]
