# Generated by Django 4.2.4 on 2024-07-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_remove_product_gst_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gst_rate",
            field=models.CharField(default="18", max_length=100),
        ),
    ]
