# Generated by Django 4.2.4 on 2024-08-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_product_gst_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(default=1)),
            ],
        ),
    ]
