# Generated by Django 4.2.4 on 2024-08-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0116_invoicenumber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartorder", options={"verbose_name_plural": "Cart Orders"},
        ),
        migrations.AddField(
            model_name="cartorder",
            name="billingaddress",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="companyname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="courier_partner",
            field=models.CharField(
                choices=[
                    ("not assigned", "NOT ASSIGNED"),
                    ("dtdc", "DTDC"),
                    ("trackon", "Trackon"),
                ],
                default="Not Assigned",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="district",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="division",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="firstname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="gst_rates_final",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=5),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="gstnumber",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="lastname",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="pin_details",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="price_wo_gst_total",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=99999),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="shippingaddress",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="tracking_id",
            field=models.CharField(default="N/A", max_length=100),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="zipcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cartorderitems",
            name="gst_rates_final",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="cartorderitems",
            name="price_wo_gst",
            field=models.DecimalField(decimal_places=2, default="0", max_digits=99999),
        ),
    ]
