# Generated by Django 4.2.4 on 2024-08-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_alter_cartorder_options_cartorder_billingaddress_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="wishlist", name="product",),
        migrations.RemoveField(model_name="wishlist", name="user",),
        migrations.DeleteModel(name="Address",),
        migrations.DeleteModel(name="Wishlist",),
    ]
