# Generated by Django 4.2.4 on 2024-08-07 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_remove_wishlist_product_remove_wishlist_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="ProductReview",),
    ]
