# Generated by Django 4.2.4 on 2024-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_alter_cartorderitems_gst_rates_final"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartorder",
            old_name="billingaddress",
            new_name="billing_address_line1",
        ),
        migrations.RenameField(
            model_name="cartorder",
            old_name="shippingaddress",
            new_name="billing_address_line2",
        ),
        migrations.AddField(
            model_name="cartorder",
            name="billing_checkout_city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="billing_checkout_district",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="billing_checkout_division",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="billing_checkout_state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="billing_street_address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="billing_zipcode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="shipping_address_line1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="shipping_address_line2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cartorder",
            name="shipping_street_address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="gst_rates_final",
            field=models.DecimalField(
                decimal_places=2, default="0.00", max_digits=99999
            ),
        ),
    ]
