# Generated by Django 4.2.4 on 2024-08-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0121_rename_billingaddress_cartorder_billing_address_line1_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartorder", name="billing_address_line1",),
        migrations.RemoveField(model_name="cartorder", name="billing_address_line2",),
        migrations.RemoveField(model_name="cartorder", name="billing_checkout_city",),
        migrations.RemoveField(
            model_name="cartorder", name="billing_checkout_district",
        ),
        migrations.RemoveField(
            model_name="cartorder", name="billing_checkout_division",
        ),
        migrations.RemoveField(model_name="cartorder", name="billing_checkout_state",),
        migrations.RemoveField(model_name="cartorder", name="billing_street_address",),
        migrations.RemoveField(model_name="cartorder", name="billing_zipcode",),
        migrations.RemoveField(model_name="cartorder", name="shipping_address_line1",),
        migrations.RemoveField(model_name="cartorder", name="shipping_address_line2",),
    ]
